version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - auth-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/authdb
      KC_DB_USERNAME: authuser
      KC_DB_PASSWORD: authpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - auth-network

  auth-service:
    build: .
    container_name: auth-service
    depends_on:
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: authpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
    ports:
      - "8080:8080"
    networks:
      - auth-network

volumes:
  pgdata:

networks:
  auth-network:
    driver: bridge
